local faber = require("faber")

local colors = {
	red = { color = "#d9595f", fallback = 1 },
	ligth_red = { color = "#f26e74", fallback = 9 },

	green = { color = "#608f73", fallback = 2 },
	light_green = { color = "#82c29c", fallback = 10 },

	yellow = { color = "#e9967e", fallback = 3 },
	light_yellow = { color = "#ecd28b", fallback = 11 },

	blue = { color = "#6791c9", fallback = 4 },
	light_blue = { color = "#7eb3f7", fallback = 12 },

	magenta = { color = "#c488ec", fallback = 5 },
	light_magenta = { color = "#e0aff0", fallback = 13 },

	cyan = { color = "#5ba8b0", fallback = 6 },
	light_cyan = { color = "#7de4f0", fallback = 14 },

	black = { color = "#061115", fallback = 0 },
	grey = { color = "#282e30", fallback = 8 },
	light_grey = { color = "#9da5a8", fallback = 7 },
	white = { color = "#edebea", fallback = 15 }
}

local groups = {
	ColorColumn = { fg = nil, bg = colors.grey, style = nil },

	Pmenu = { fg = nil, bg = colors.grey, style = nil },
	PmenuSel = { fg = nil, bg = nil, style = nil },
	PmenuSbar = { fg = nil, bg = colors.white, style = nil },
	PmenuThumb = { fg = nil, bg = colors.black, style = nil },

	CmpItemAbbr = { fg = colors.light_grey, bg = nil, style = nil },
	CmpItemAbbrDeprecated = { fg = colors.grey, bg = nil, style = nil },
	CmpItemAbbrMatch = { fg = colors.white, bg = nil, style = nil },
	CmpItemKind = { fg = colors.yellow, bg = nil, style = nil },

	TSAttribute = { fg = colors.red, bg = nil, style = nil },
	TSBoolean = { fg = colors.cyan, bg = nil, style = nil },
	TSCharacter = { fg = colors.light_yellow, bg = nil, style = faber.styles.italic },
	TSCharacterSpecial = { fg = colors.light_yellow, bg = nil, style = faber.styles.standout },
	TSComment = { fg = colors.light_grey, bg = nil, style = nil },
	TSConditional = { fg = colors.yellow, bg = nil, style = nil },
	TSConstant = { fg = colors.red, bg = nil, style = faber.styles.italic },
	TSConstBuiltin = { fg = colors.red, bg = nil, style = faber.styles.italic },
	TSConstMacro = { fg = colors.red, bg = nil, style = faber.styles.italic },
	TSDebug = { fg = colors.light_grey, bg = nil, style = nil },
	TSDefine = { fg = colors.magenta, bg = nil, style = nil },
	TSField = { fg = colors.cyan, bg = nil, style = faber.styles.none },
	TSFloat = { fg = nil, bg = colors.white, style = nil },
	TSFunction = { fg = colors.light_cyan, bg = nil, style = nil },
	TSFuncBuiltin = { fg = colors.light_cyan, bg = nil, style = nil },
	TSFuncMacro = { fg = colors.light_cyan, bg = nil, style = nil },
	TSInclude = { fg = colors.yellow, bg = nil, style = nil },
	TSKeyword = { fg = colors.light_magenta, bg = nil, style = nil },
	TSKeywordFunction = { fg = colors.light_magenta, bg = nil, style = nil },
	TSKeywordOperator = { fg = colors.light_magenta, bg = nil, style = nil },
	TSKeywordReturn = { fg = colors.light_magenta, bg = nil, style = nil },
	TSLabel = { fg = colors.light_magenta, bg = nil, style = nil },
	TSMethod = { fg = colors.light_green, bg = nil, style = nil },
	TSNamespace = { fg = colors.blue, bg = nil, style = nil },
	TSNumber = { fg = colors.white, bg = nil, style = nil },
	TSOperator = { fg = colors.white, bg = nil, style = nil },
	TSParameter = { fg = colors.cyan, bg = nil, style = nil },
	TSParameterReference = { fg = colors.cyan, bg = nil, style = nil },
	TSPreProc = { fg = colors.magenta, bg = nil, style = nil },
	TSProperty = { fg = colors.cyan, bg = nil, style = nil },
	TSPunctDelimiter = { fg = colors.yellow, bg = nil, style = nil },
	TSPunctBracket = { fg = colors.light_blue, bg = nil, style = nil },
	TSPunctSpecial = { fg = colors.light_blue, bg = nil, style = nil },
	TSRepeat = { fg = colors.light_yellow, bg = nil, style = nil },
	TSStorageClass = { fg = colors.green, bg = nil, style = nil },
	TSString = { fg = colors.light_yellow, bg = nil, style = faber.styles.italic },
	TSStringRegex = { fg = colors.red, bg = nil, style = nil },
	TSStringEscape = { fg = colors.red, bg = nil, style = nil },
	TSStringSpecial = { fg = colors.red, bg = nil, style = nil },
	TSSymbol = { fg = colors.light_green, bg = nil, style = nil },
	TSTag = { fg = colors.blue, bg = nil, style = nil },
	TSTagAttribute = { fg = colors.yellow, bg = nil, style = nil },
	TSTagDelimiter = { fg = colors.light_yellow, bg = nil, style = nil },
	TSText = { fg = colors.white, bg = nil, style = nil },
	TSStrong = { fg = colors.white, bg = nil, style = faber.styles.bold },
	TSEmphasis = { fg = colors.white, bg = nil, style = faber.styles.italic },
	TSUnderline = { fg = colors.white, bg = nil, style = faber.styles.underline },
	TSStrike = { fg = colors.white, bg = nil, style = faber.styles.strikethrough },
	TSTitle = { fg = colors.white, bg = nil, style = faber.styles.underlineline },
	TSLiteral = { fg = colors.white, bg = nil, style = nil },
	TSURI = { fg = colors.light_green, bg = nil, style = faber.styles.italic },
	TSMath = { fg = colors.light_green, bg = nil, style = faber.styles.bold },
	TSTextReference = { fg = colors.white, bg = nil, style = faber.styles.italic },
	TSEnvironment = { fg = colors.white, bg = nil, style = nil },
	TSNote = { fg = colors.light_grey, bg = nil, style = nil },
	TSWarning = { fg = colors.light_red, bg = nil, style = faber.styles.underdash },
	TSDanger = { fg = colors.ligth_red, bg = nil, style = faber.styles.undercurl },
	TSTodo = { fg = colors.white, bg = nil, style = nil },
	TSType = { fg = colors.green, bg = nil, style = nil },
	TSTypeBuiltin = { fg = colors.green, bg = nil, style = nil },
	TSTypeQualifier = { fg = colors.light_green, bg = nil, style = nil },
	TSTypeDefinition = { fg = colors.magenta, bg = nil, style = nil },
	TSVariable = { fg = colors.white, bg = nil, style = faber.styles.italic },
	TSVariableBuiltin = { fg = colors.white, bg = nil, style = faber.styles.italic },
}

faber.register_colors(colors)
faber.add_highlight_groups(groups)
